[package]
name = "creek"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" , features = ["raw_value"] }
futures = { version = "0.3.17" }
tokio = {version = "1.12.0", features = ["full"] }